csvs/urls.py
from django.urls import path
from .views import upload_file_view,upload_nba_file_view

app_name = 'csvs'

urlpatterns = [
    path('ncaa_upload/', upload_file_view, name='upload-view'),
    path('nba_upload/', upload_nba_file_view,name='upload-nba-view')
]

nba/urls.py
from django.urls import path
from .views import shot_chart_view,shot_graphs_view

app_name = 'nba'

urlpatterns = [
    path('',shot_chart_view,name='shot-chart-view'),
    path('nba_graphs/',shot_graphs_view,name="shot-graph-view")
]

ncaa_analytics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include('csvs.urls', namespace='csvs')),
    path('correlation/', include('ncaa_basketball.urls',namespace='ncaa_basketball')),
    path('shot_chart/',include('nba.urls',namespace='nba'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

ncaa_basketball/urls.py
from django.urls import path
from .views import winning_correlation_view

app_name = 'ncaa_basketball'

urlpatterns = [
    path('',winning_correlation_view,name='winning-correlation-view'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel='stylesheet' type='text/css' href={% static 'style.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>DJ PD Proj - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class='ui container'>
    {% block content %}
    {% endblock content %}
    </div>
   
   <script type='text/javascript' src={% static 'main.js' %}></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home{% endblock title %}

{% block content %}
<div class='block-center'>
    <img src={% static 'main_pic.jpg' %} class='ui fluid image'>
</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block title %}login{% endblock title %}

{% block content %}
<div class='block-center'>
    {% if error_message %}
        <div class="ui negative message">
            <i class="close icon"></i>
            <div class="header">
                {{ error_message }}
            </div>
        </div>
    {% endif %}
    <form action="" method="POST" class="ui form" autocomplete="off">
        {% csrf_token %}
        {{ form }}
        <button type='submit' class="ui button positive mtop">Login</button>
    </form>
</div>
{% endblock content %}

templates/navbar.html
{% url 'ncaa_basketball:winning-correlation-view' as path_to_correlations %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'csvs:upload-nba-view' as path_to_nba_upload %}
{% url 'nba:shot-chart-view' as path_to_shot_chart %}
{% url 'nba:shot-graph-view' as path_to_shot_graph %}


<div class="ui secondary pointing menu">
  <a href={{path_to_shot_chart}} class="{% if request.path == path_to_shot_chart%}active{% endif %} item">
  NBA Shot Charts
  </a>
   <a href={{path_to_shot_graph}} class="{% if request.path == path_to_shot_graph%}active{% endif %} item">
  NBA Shot Graphs
  </a>
  <a href={{path_to_correlations}} class="{% if request.path == path_to_correlations%}active{% endif %} item">
  NCAA Charts
  </a>
  <a href={{path_to_upload}} class="{% if request.path == path_to_upload%}active{% endif %} item">
  Upload NCAA Stats
  </a>
  <a href={{path_to_nba_upload}} class="{% if request.path == path_to_nba_upload%}active{% endif %} item">
  Upload NBA Shots
  </a>
</div>